#!/bin/bash

DOCKERFILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR=${DOCKERFILE_DIR%/*/*}

cd ../../frontend/
docker build -t frontend_$(git rev-parse --short HEAD):dev -f ../containers/frontend/Dockerfile ./
docker run --rm --name frontend -it -v ${PROJECT_DIR}/frontend/:/app -v /app/node_modules -p 3000:3000 -e CHOKIDAR_USEPOLLING=true frontend_$(git rev-parse --short HEAD):dev
cd ../containers/frontend
