info:
  contact: {}
  description: |-
    This is CS-GO Backend Server
    Server provides service for players that want to practise their skills and improve it
  license: {}
  title: Swagger CS-GO Backend API
  version: "0.1"
definitions:
  user:
    type: object
    properties:
      ID:
        type: integer
        format: int64
        readOnly: true
      Username:
        type: string
        format: string
      Email:
        type: string
        format: string
      Password:
        type: string
        format: string
      Avatar:
        type: string
        format: string
paths: {}
swagger: "2.0"